# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Migrate

on:
  workflow_dispatch:
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Azure subscriptionId
        # subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - run: npm install
    - run: cd scripts.v3
    - run: node ./capture --subscriptionId ${{ secrets.SUBSCRIPTIONID }} --resourceGroupName "test-apim" --serviceName "meo-apim"
    
    
